routes/web.php
<?php
		// $connection = new mysqli("localhost","root","","projectems");
		// $stet = $connection->prepare("select * from exhibtions");
		// $stet->execute();
		// $result = $stet->get_result();
		// while ($row = $result->fetch_assoc()) {
		// echo $row["Exhibition_Name"];
		// }
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function(){ 


Route::get('/', function () {
    return view('welcome');
});

Route::resource('Adminex','AdminexController');

Route::resource('Exhibtions','ExhibtionsController');

Route::resource('Buy','BuyController');

//Route::get('Merch', [ 'as' => 'Merch', 'uses' => 'MerchController@index']);

//Route::resource('Merch', 'MerchController');
Route::resource('Merch','MerchController' );
//Route::get('/home', 'MerchController@index')->name('home');



//Route::get('/home', 'HomeController@index')->name('home');


Route::resource('Admin','AdminController');

Route::resource('Category','CategoryController');

Route::get('finish', 'Lincontroller@finish');


Route::get('start', 'Lincontroller@start');

Route::resource('Contact','ContactController')->only(['create', 'store', 'index', 'thank']);

Route::resource('Product','ProductController');







	

	
});


Auth::routes();




Route::post('checklogin', 'SessionController@checklogin');
Route::get('login/success', 'SessionController@success');
Route::get('login/logout', 'SessionController@logout');
//Auth::routes();


Route::get('/home', function () {

	if(Auth::user()->isAdmin)
        return redirect()->route('Merch.index');
	else  return redirect()->route('Product.index');

});


Route::get('/wael', function () {
    if(Auth::user()->isAdmin)
        return redirect()->route('Product.index');

    return view('login');
});

resources/views/finish.blade.php
@extends('layou.app')
@section('content')

    <section class="projects-clean" style="height: 1070px;margin: 52px;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center" style="color: var(--bs-green);">@lang('The.Finished Exhibition')<i class="material-icons" style="font-size: 42px;color: var(--bs-red);margin: 1px;">timer_off</i></h2>
                <p class="text-center">@lang('The.Browse Expired Exhibitions')</p>
            </div>
            <div class="row Exhibition">
            @foreach($exhibtions as $exhibtion)
            @if($exhibtion->state == 'finish')
                <div class="col item">
                    <a href="{{route('Exhibtions.index', ['id' => $exhibtion->id])}}"> 
                        <img class="img-fluid" src="/Exhibition/{{$exhibtion->Exhibition_Name}}.jpg"></a>

                        <h3 class="name">{{$exhibtion->Exhibition_Name}}   Exhibition</h3><span></span>
                    <h5>@lang('The.Date') </h5> <span>{{$exhibtion->created_at}}</span>               
            </div>
            @endif
            @endforeach
        </div>
    </section>

    
             
    </div>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/0b51cec2d899412ea501d9269bffcda03dbf932c25e343a4b206a355923ba199.js"></script>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login - EM-S-ITE</title>
    <link rel="stylesheet" href="/assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="/assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="/assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="/assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="/assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="/assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="/assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="/assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/Image_center.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Map-Clean.css">
    <link rel="stylesheet" href="/assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element.css">
    <link rel="stylesheet" href="/assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="/assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="/assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css">
    <link rel="icon" href="/assets/img/logo.png" type="image/x-icon">

</head>

<body style="background: var(--bs-white);">
    <section class="border rounded-pill login-clean" style="background: url(&quot;/assets/img/exhibitions-gl-events.jpg&quot;);">
        <form data-aos="zoom-in" data-aos-duration="500" data-aos-delay="50" method="post" action="/checklogin" style="height: 550px;">
            {{csrf_field()}}
            <h2 class="visually-hidden">Login Form</h2>
            <div class="illustration"><img src="/assets/img/f29a1ebaf6ba41c8871ee1ace3098555.png"></div>
            <div class="mb-3"><input class="form-control" type="email" name="email" placeholder="Email"></div>
            <div class="mb-3"><input class="form-control" type="password" name="password" placeholder="Password"></div>
            <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit" style="background: var(--bs-green);">Log In</button></div><a class="forgot" href="#">Forgot your email or password?</a>
        </form>
    </section>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="height: 11%;width: 100%;">
        <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><i class="fa fa-th-list"></i></button><img data-aos="fade" data-aos-delay="100" data-aos-once="true" src="/assets/img/logo.png" style="width: 90px;height: 70px;margin: -20px;padding: 0px;font-size: 17px;"><img src="/assets/img/EMSITE.png" style="height: 41px;width: 153px;margin: 1px 0px;padding: 0px 0px;">
            <div class="collapse navbar-collapse" id="navcol-1" style="height: 40px;width: 979.7px;">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="/start" style="width: 43px;">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Contact.create')}}">Contact - us</a></li>
                    <li class="nav-item"><a class="nav-link" href="/finish">Our works</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Exhibtions.create')}}">Live exhibitions</a></li>
                    <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Merch.create')}}">Merch</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div id="footer" class="flex-wrap">
        <div id="image-box" class="col"><img id="footer-img" src="/assets/img/unnamed.png"></div>
        <div id="end-box" class="col">
            <div id="end-content">
                <a href="/live.html"><h1 style="color: rgb(255,255,255);">Our works</h1></a>
                <ul class="list-unstyled">
                    <li style="color: rgb(255,255,255);font-size: 19px;">Phone:&nbsp;<a href="tel:+963932895825"><span style="color: rgb(69,73,78);">+963932895825</span></a><br></li>
                    <li style="color: rgb(255,255,255);font-size: 19px;">E-Mail:&nbsp;<a href="mailto:Syrjara@gmail.com"><span style="color: rgb(69,73,78);">syrjara@gmail.com</span></a><br></li>
                </ul> <a href="/contact-us.html"> <button class="btn btn-primary" id="form-btn" type="button"><i class="fa fa-envelope-o"></i>&nbsp;Contact-us</button></a>
                <div id="info-some-buttons" class="some" style="display: flex;justify-content: center;">
                    <ul class="some-list">
                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                        <li class="whatsapp"><a href="https://wa.link/"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/0b51cec2d899412ea501d9269bffcda03dbf932c25e343a4b206a355923ba199.js"></script>

</body>

</html>

resources/views/thank.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Thank you</title>
    <link rel="stylesheet" href="/assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="/assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="/assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="/assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="/assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="/assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="/assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="/assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/Image_center.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Map-Clean.css">
    <link rel="stylesheet" href="/assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element.css">
    <link rel="stylesheet" href="/assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="/assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="/assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css">
    <link rel="icon" href="/assets/img/logo.png" type="image/x-icon">

</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="height: 11%;width: 100%;">
        <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><i class="fa fa-th-list"></i></button><img data-aos="fade" data-aos-delay="100" data-aos-once="true" src="/assets/img/logo.png"
                style="width: 90px;height: 70px;margin: -20px;padding: 0px;font-size: 17px;"><img src="/assets/img/EMSITE.png" style="height: 41px;width: 153px;margin: 1px 0px;padding: 0px 0px;">
            <div class="collapse navbar-collapse" id="navcol-1" style="height: 40px;width: 979.7px;">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="/start" style="width: 90px;">@lang('The.HOME')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Contact.create')}}">@lang('The.CONTACT-US')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/finish">@lang('The.OUR WORKS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Exhibtions.create')}}">@lang('The.LIVE EXHIBITIONS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/login">@lang('The.LOGIN')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Merch.create')}}">@lang('The.Merch')</a></li>


               

</ul>

             

            </div>
        </div>
    </nav>
    <section data-bss-parallax-bg="true" class="clean-block clean-hero" style="color: rgba(0,0,0,0.85);background: url(&quot;/assets/img/exhibitions-gl-events.jpg&quot;) center / auto no-repeat;border-color: var(--bs-white);filter: brightness(106%);background-image: url(/assets/img/exhibitions-gl-events.jpg);background-position: center;background-size: cover;">
        <div class="text">
            <h2 style="font-size: 90px;">@lang('The.Thank You !')</h2>
            <p>@lang('The.You’ve successfully submitted your information. We will be in touch shortly!')<br></p>
        </div>
        
    </section>
    <div id="footer" class="flex-wrap">
        <div id="image-box" class="col"><img id="footer-img" src="/assets/img/unnamed.png"></div>
        <div id="end-box" class="col">
            <div id="end-content">
                <a href="/live.html"><h1 style="color: rgb(255,255,255);">Our works</h1></a>
                <ul class="list-unstyled">
                    <li style="color: rgb(255,255,255);font-size: 19px;">Phone:&nbsp;<a href="tel:+963932895825"><span style="color: rgb(69,73,78);">+963932895825</span></a><br></li>
                    <li style="color: rgb(255,255,255);font-size: 19px;">E-Mail:&nbsp;<a href="mailto:Syrjara@gmail.com"><span style="color: rgb(69,73,78);">syrjara@gmail.com</span></a><br></li>
                </ul> <a href="/contact-us.html"> <button class="btn btn-primary" id="form-btn" type="button"><i class="fa fa-envelope-o"></i>&nbsp;Contact-us</button></a>
                <div id="info-some-buttons" class="some" style="display: flex;justify-content: center;">
                    <ul class="some-list">
                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                        <li class="whatsapp"><a href="https://wa.link/"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <script src="/assets/js/time-out.js"></script>
</body>

</html>