routes/web.php
<?php
		// $connection = new mysqli("localhost","root","","projectems");
		// $stet = $connection->prepare("select * from exhibtions");
		// $stet->execute();
		// $result = $stet->get_result();
		// while ($row = $result->fetch_assoc()) {
		// echo $row["Exhibition_Name"];
		// }
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function(){ 


Route::get('/', function () {
    return view('welcome');
});

Route::resource('Adminex','AdminexController');

Route::resource('Exhibtions','ExhibtionsController');

Route::resource('Buy','BuyController');

//Route::get('Merch', [ 'as' => 'Merch', 'uses' => 'MerchController@index']);

//Route::resource('Merch', 'MerchController');
Route::resource('Merch','MerchController' );
//Route::get('/home', 'MerchController@index')->name('home');



//Route::get('/home', 'HomeController@index')->name('home');


Route::resource('Admin','AdminController');

Route::resource('Category','CategoryController');

Route::get('finish', 'Lincontroller@finish');


Route::get('start', 'Lincontroller@start');

Route::resource('Contact','ContactController')->only(['create', 'store', 'index', 'thank']);

Route::resource('Product','ProductController');







	

	
});


Auth::routes();




Route::post('checklogin', 'SessionController@checklogin');
Route::get('login/success', 'SessionController@success');
Route::get('login/logout', 'SessionController@logout');
//Auth::routes();


Route::get('/home', function () {

	if(Auth::user()->isAdmin)
        return redirect()->route('Merch.index');
	else  return redirect()->route('Product.index');

});


Route::get('/wael', function () {
    if(Auth::user()->isAdmin)
        return redirect()->route('Product.index');

    return view('login');
});

resources/views/layou/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Exhibition Name</title>
    <link rel="stylesheet" href="/assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="/assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="/assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="/assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="/assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="/assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="/assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="/assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/Image_center.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Map-Clean.css">
    <link rel="stylesheet" href="/assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element.css">
    <link rel="stylesheet" href="/assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="/assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="/assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css">
    <link rel="stylesheet" href="/assets/css/hide-and-show.css">
    <link rel="icon" href="/assets/img/logo.png" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="height: 11%;width: 100%;">
        <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><i class="fa fa-th-list"></i></button><img data-aos="fade" data-aos-delay="100" data-aos-once="true" src="/assets/img/logo.png"
                style="width: 90px;height: 70px;margin: -20px;padding: 0px;font-size: 17px;"><img src="/assets/img/EMSITE.png" style="height: 41px;width: 153px;margin: 1px 0px;padding: 0px 0px;">
            <div class="collapse navbar-collapse" id="navcol-1" style="height: 40px;width: 979.7px;">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="/start" style="width: 90px;">@lang('The.HOME')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Contact.create')}}">@lang('The.CONTACT-US')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/finish">@lang('The.OUR WORKS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Exhibtions.create')}}">@lang('The.LIVE EXHIBITIONS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/login">@lang('The.LOGIN')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Merch.create')}}">@lang('The.Merch')</a></li>


               

</ul>
<div class="dropdown"><button class="btn btn-primary dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button">Language </button>
    <div class="dropdown-menu">
    <ul>
        @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
           <li>
            <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
             {{ $properties['native'] }}
            </a>
            </li>
        @endforeach
    </ul>
    </ul>
            </div>
    </div>
             

            </div>
        </div>
    </nav>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <section>



@yield('content')



 <div id="footer" class="flex-wrap">
        <div id="image-box" class="col"><img id="footer-img" src="/assets/img/unnamed.png"></div>
        <div id="end-box" class="col">
            <div id="end-content">
                <ul class="list-unstyled">
                    <li style="color: rgb(255,255,255);font-size: 19px;">@lang('The.Phone:')&nbsp;<a href="tel:+963932895825"><span style="color: rgb(69,73,78);">+963932895825</span></a><br></li>
                    <li style="color: rgb(255,255,255);font-size: 19px;">@lang('The.E-Mail:')&nbsp;<a href="mailto:Syrjara@gmail.com"><span style="color: rgb(69,73,78);">syrjara@gmail.com</span></a><br></li>
                </ul> 
                <div id="info-some-buttons" class="some" style="display: flex;justify-content: center;">
                    <ul class="some-list">
                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                        <li class="whatsapp"><a href="https://wa.link/"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <script src="/assets/bootstrap/js/bootstrap.min.js "></script>
    <script src="/assets/js/bs-init.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js "></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js "></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js "></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js "></script>
    <script src="/assets/js/vanilla-zoom.js "></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js "></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js "></script>
    <script src="/assets/js/theme.js "></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js "></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js "></script>
    <script src="/assets/js/Panel-Element-1.js "></script>
    <script src="/assets/js/Panel-Element.js "></script>
    <script src="/assets/js/Simple-Side-Nav.js "></script>
    <script src="/assets/js/Simple-Slider.js "></script>
    <script src="/assets/js/raphael-min.js "></script>
    <script src="/assets/js/move.js "></script>
    <script src="//assets/js/zoommap.js"></script>
    <script src="//assets/js/hideshow.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="jquery.zoomooz.min.js"></script>


    <script>
        function openTab(tabName) {
        var i, x;
        x = document.getElementsByClassName("containerTab");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            document.getElementById(tabName).style.display = "block";
        }
    </script>
</body>

</html>

resources/views/layou/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Dashboard Exibition Manage</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="DashboardKit is made using Bootstrap 5 design framework. Download the free admin template & use it for your project.">
    <meta name="keywords" content="DashboardKit, Dashboard Kit, Dashboard UI Kit, Bootstrap 5, Admin Template, Admin Dashboard, CRM, CMS, Free Bootstrap Admin Template">
    <meta name="author" content="DashboardKit ">


    <link rel="icon" href="/asset/images/logo.png" type="image/x-icon">

    <link rel="stylesheet" href="/asset/fonts/feather.css">
    <link rel="stylesheet" href="/asset/fonts/fontawesome.css">
    <link rel="stylesheet" href="/asset/fonts/material.css">

    <link rel="stylesheet" href="/asset/css/style.css" id="main-style-link">

</head>
<body>
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>
    <div class="pc-mob-header pc-header">
        <div class="pcm-logo">
            <img src="/asset/images/logo.png" style="width: 75px;" class="logo logo-lg"> @lang('The.Dashboard')
        </div>
        <div class="pcm-toolbar">
            <a href="#!" class="pc-head-link" id="mobile-collapse">
                <div class="hamburger hamburger--arrowturn">
                    <div class="hamburger-box">
                        <div class="hamburger-inner"></div>
                    </div>
                </div>
            </a>
            <a href="#!" class="pc-head-link" id="headerdrp-collapse">
                <i data-feather="align-right"></i>
            </a>
            <a href="#!" class="pc-head-link" id="header-collapse">
                <i data-feather="more-vertical"></i>
            </a>
        </div>
    </div>

    <nav class="pc-sidebar ">
        <div class="navbar-wrapper">
            <div class="m-header">
                <a href="/start" class="b-brand">
                    <img src="/asset/images/logo.png" style="width: 75px;" class="logo logo-lg">@lang('The.Dashboard Exhibitioin')
                    <img src="/asset/images/logo.png" alt="" class="logo logo-sm">
                </a>
            </div>
            <div class="navbar-content">
                <ul class="pc-navbar">
                    
                    <li class="pc-item">
                        <a href="{{route('Adminex.create')}}" class="pc-link ">
                            <span class="pc-micon">
                                <i class="material-icons-two-tone">add</i>
                            </span>
                            <span class="pc-mtext">@lang('The.Create')</span>
                        </a>
                    </li>

                    <li class="pc-item">
                        <a href="{{route('Adminex.index')}}" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">settings</i>
                        </span>
                        <span class="pc-mtext">@lang('The.Manage')</span>
                    </a>
                    </li>

                    <li class="pc-item">
                        <a href="{{route('Merch.index')}}" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">person</i></span><span class="pc-mtext">@lang('The.Merches')</span></a>
                    </li>

                    <li class="pc-item">
                        <a href="{{route('Contact.index')}}" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">messenger</i></span><span class="pc-mtext">@lang('The.Contact')</span></a>
                    </li>
                    <li class="pc-item">
                        <a href="{{route('Buy.create')}}" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">shop</i></span><span class="pc-mtext">@lang('The.Buy orders')</span></a>
                    </li>
                </ul>

            </div>

        </div>
        
    </nav>

    
<script src="/asset/js/vendor-all.min.js"></script>
    <script src="/asset/js/plugins/bootstrap.min.js"></script>
    <script src="/asset/js/plugins/feather.min.js"></script>
    <script src="/asset/js/pcoded.min.js"></script>

<script src="/asset/js/plugins/apexcharts.min.js"></script>

@yield('content')
<script src="/asset/js/pages/dashboard-sale.js"></script>
 <script src="/asset/js/vendor-all.min.js"></script>
    <script src="/asset/js/plugins/bootstrap.min.js"></script>
    <script src="/asset/js/plugins/feather.min.js"></script>
    <script src="/asset/js/pcoded.min.js"></script>

<script src="/asset/js/plugins/apexcharts.min.js"></script>

<script src="/asset/js/pages/dashboard-sale.js"></script>
</body>

</html>