routes/web.php
<?php
		// $connection = new mysqli("localhost","root","","projectems");
		// $stet = $connection->prepare("select * from exhibtions");
		// $stet->execute();
		// $result = $stet->get_result();
		// while ($row = $result->fetch_assoc()) {
		// echo $row["Exhibition_Name"];
		// }
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function(){ 


Route::get('/', function () {
    return view('welcome');
});

Route::resource('Adminex','AdminexController');

Route::resource('Exhibtions','ExhibtionsController');

Route::resource('Buy','BuyController');

//Route::get('Merch', [ 'as' => 'Merch', 'uses' => 'MerchController@index']);

//Route::resource('Merch', 'MerchController');
Route::resource('Merch','MerchController' );
//Route::get('/home', 'MerchController@index')->name('home');



//Route::get('/home', 'HomeController@index')->name('home');


Route::resource('Admin','AdminController');

Route::resource('Category','CategoryController');

Route::get('finish', 'Lincontroller@finish');


Route::get('start', 'Lincontroller@start');

Route::resource('Contact','ContactController')->only(['create', 'store', 'index', 'thank']);

Route::resource('Product','ProductController');







	

	
});


Auth::routes();




Route::post('checklogin', 'SessionController@checklogin');
Route::get('login/success', 'SessionController@success');
Route::get('login/logout', 'SessionController@logout');
//Auth::routes();


Route::get('/home', function () {

	if(Auth::user()->isAdmin)
        return redirect()->route('Merch.index');
	else  return redirect()->route('Product.index');

});


Route::get('/wael', function () {
    if(Auth::user()->isAdmin)
        return redirect()->route('Product.index');

    return view('login');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['Brand', 'Model', 'Price', 'Warranty', 'Description','merch_id' ,'image1', 'image2','image3','image4'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Merch;
use App\Product;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $adminex = DB::select('select * from adminexes ');

        $categories = DB::select('select * from categories ');


        if(Auth::check() == false)
            return view('login');

        $merch = Merch::where('Email' , Auth::user()->email )->first();
        $products = Product::where('merch_id' , $merch->id)->get();

        return view('Products.index',compact('products'),['adminex'=>$adminex, 'categories'=>$categories, 'products'=>$products  , 'merch'=>$merch]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        if($request->search){
        
        $search = $request->get('search');
        $products = DB::table('products')->where('Brand', 'like' , '%' . $search . '%')->paginate(5);
        return view('Products.create',['products'=>$products]);
        }

        $products = DB::select('select * from products WHERE merch_id = ' . $request->id);


        return view('Products.create', ['products'=>$products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $request -> validate([

        "Brand"=>"required:products,Brand",
        "Model"=>"required:products,Model",
        "Price"=>"required:products,Price",
        "Warranty"=>"required:products,Warranty",
        "Description"=>"required:products,Description",
        "image1"=>"required:products,image1",
        "image2"=>"required:products,image2",
        "image3"=>"required:products,image3",
        "image4"=>"required:products,image4",

        ]);
        $imageName1 = $request->Model . '1' .'.' .request()->image1->getClientOriginalExtension();
        request()->image1->move(public_path('ProductsImage'), $imageName1);

        $imageName2 = $request->Model  . '2' .  '.' .request()->image2->getClientOriginalExtension();
        request()->image2->move(public_path('ProductsImage'), $imageName2);

        $imageName3 = $request->Model . '3'. '.' .request()->image3->getClientOriginalExtension();
        request()->image3->move(public_path('ProductsImage'), $imageName3);

        $imageName4 = $request->Model.'4' .  '.' .request()->image4->getClientOriginalExtension();
        request()->image4->move(public_path('ProductsImage'), $imageName4);

        $data = $request->all();

        $data['merch_id'] = Merch::where('Email' , Auth::user()->email)->first()->id;

        Product::create($data);
        session()->flash('success',__('success'));
        return redirect()->route('Product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('Products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
      $admain = Product::find($id);
      $admain->Brand = $request->get('Brand');
      $admain->Model = $request->get('Model');
      $admain->Price = $request->get('Price');
      $admain->Warranty = $request->get('Warranty');
      $admain->Description = $request->get('Description');
      $admain->save();
        
  
        return redirect()->route('Product.index');   
         }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $blog = Product::findOrFail($id);

        $blog->delete();

        return redirect()->route('Product.index');
    }
}

resources/views/Products/create.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home</title>
    <link rel="stylesheet" href="assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="/assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="/assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="/assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="/assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="/assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="/assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="/assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/Image_center.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Map-Clean.css">
    <link rel="stylesheet" href="/assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element.css">
    <link rel="stylesheet" href="/assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="/assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="/assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css">
    <link rel="icon" href="/assets/img/logo.png" type="image/x-icon">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md" id="app-navbar">
        <div class="container-fluid"><a class="navbar-brand" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" id="brand-logo">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M5.79166 2H1V4H4.2184L6.9872 16.6776H7V17H20V16.7519L22.1932 7.09095L22.5308 6H6.6552L6.08485 3.38852L5.79166 2ZM19.9869 8H7.092L8.62081 15H18.3978L19.9869 8Z" fill="currentColor"></path>
                    <path d="M10 22C11.1046 22 12 21.1046 12 20C12 18.8954 11.1046 18 10 18C8.89543 18 8 18.8954 8 20C8 21.1046 8.89543 22 10 22Z" fill="currentColor"></path>
                    <path d="M19 20C19 21.1046 18.1046 22 17 22C15.8954 22 15 21.1046 15 20C15 18.8954 15.8954 18 17 18C18.1046 18 19 18.8954 19 20Z" fill="currentColor"></path>
                </svg></a>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link active" href="/start">@lang('The.Home')</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{{route('Contact.create')}}">@lang('The.Contact - Us')</a></li>
                    <li class="nav-item"></li>
                    <li>
                        <div class="px-3">
                            <form action="{{route('Product.create')}}" method="get">
                                <div class="form-group mb-0 d-flex align-items-center">
                                    <i data-feather="search"></i>
                                    <input type="search" name="search" class="form-control border-0 shadow-none" placeholder="Search here. . .">
                                </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section>
        <section style="width: 100%;height: 100%;">
            <div>
                <header class="header-dark" style="padding: 0px;">
                    

                    <div class="row" style="width: 98%;margin: 0px 1%;">

                    @foreach($products as $product)
                            <div class="col-md-6" style="padding: 10px;margin: 0px 5px;width: 400px;">
                                    <div class="card device-card" style="width: 100%;">
                                        <div class="card-body" style="width: 350px;height: 320px; margin: 0px;padding: 16px;">
                                            <h6 class="card-title"><strong>@lang('The.Brand') </strong>: {{$product->Brand}}<br></h6>
                                            <h6 class="card-title"><strong>@lang('The.Model') </strong>: {{$product->Model}} <br></h6>
                                            <h6 class="card-title"><strong> @lang('The.Warranty : ') </strong> {{$product->Warranty}} <br></h6>
                                            <h6 class="card-title"><strong> @lang('The.Description') </strong>: {{$product->Description}}<br></h6>
                                            <div class="modal-footer">
                                            <a href="{{route('Buy.index',['id'=> $product->id])}}">
                                            	<button class="btn btn-light" id="btnSaveModalitem" type="button" data-bs-dismiss="modal" style="  background: var(--bs-cyan);" onclick="location">@lang('The.Buy')</button>
                                            </a>
                                        </div>
                                            <p class="card-text" style="margin: 0px;height: 30px;font-size: 15px;">@lang('The.Price: ') : {{$product->Price}}</p>
                                        </div>                                        
                                    </div>
                            </div>     
                            @endforeach
                  
                    </div>
                </header>
            </div>
        </section>
    </section>


    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/0b51cec2d899412ea501d9269bffcda03dbf932c25e343a4b206a355923ba199.js"></script>

</body>

</html>

resources/views/Products/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Edit</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/FPE-Gentella-form-elements-1.css">
    <link rel="stylesheet" href="/assets/css/FPE-Gentella-form-elements.css">
    <link rel="stylesheet" href="/assets/css/Pretty-Registration-Form.css">
    <link rel="stylesheet" href="/assets/css/Pretty-Search-Form.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
</head>

<body style="background: var(--bs-success);">
    <div class="row register-form">
        <div class="col-md-8 offset-md-2">
            <form method="post" action="{{ route('Product.update', $product->id) }}" class="custom-form" >
                @method('PATCH')
                @csrf
                <h1 style="font-size: 58px;">Edit Form</h1>
                <div class="row form-group">
                    <div class="col-sm-4 label-column">
                        <label class="col-form-label">Brand </label></div>
                    <div class="col-sm-6 input-column">
                        <input class="form-control" name="Brand" type="text" value="{{$product->Brand}}"></div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-4 label-column"><label class="col-form-label" >Model</label></div>
                    <div class="col-sm-6 input-column"><input class="form-control" name="Model" type="text" value="{{$product->Model}}"></div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-4 label-column">
                        <label class="col-form-label" >Warranty</label></div>
                    <div class="col-sm-6 input-column">
                        <input class="form-control" name="Warranty" type="text" value="{{$product->Warranty}}" ></div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-4 label-column"><label class="col-form-label" >Description</label></div>
                    <div class="col-sm-6 input-column" style="width: 292px;height: 65px;">
                        <input class="form-control" name="Description" type="text" style="height: 63px;" value="{{$product->Description}}"></div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-4 label-column"><label class="col-form-label" >Price</label></div>
                    <div class="col-sm-6 input-column">
                        <input class="form-control" type="number" name="Price" value="{{$product->Price}}"></div>
                </div>
                <button class="btn btn-light submit-button" type="Submit" value="edit">Submit&nbsp;</button>
            </form>
        </div>
    </div>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

resources/views/Products/show.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Buy it  - EM-S-ITE</title>
    <link rel="stylesheet" href="assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="assets/css/Image-Tab-Gallery-Horizontal.css">
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="assets/css/Image_center.css">
    <link rel="stylesheet" href="assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="assets/css/Map-Clean.css">
    <link rel="stylesheet" href="assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="assets/css/Panel-Element.css">
    <link rel="stylesheet" href="assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="assets/css/vanilla-zoom.min.css">
    <link rel="icon" href="assets/img/logo.png" type="image/x-icon">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="height: 11%;width: 100%;">
        <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><i class="fa fa-th-list"></i></button><img data-aos="fade" data-aos-delay="100" data-aos-once="true" src="assets/img/logo.png" style="width: 90px;height: 70px;margin: -20px;padding: 0px;font-size: 17px;"><img src="assets/img/EMSITE.png" style="height: 41px;width: 153px;margin: 1px 0px;padding: 0px 0px;">
            <div class="collapse navbar-collapse" id="navcol-1" style="height: 40px;width: 979.7px;">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="index.html" style="width: 43px;">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" href="contact-us.html">Contact - us</a></li>
                    <li class="nav-item"><a class="nav-link" href="finished.html">our works</a></li>
                    <li class="nav-item"><a class="nav-link" href="live.html">Live exhibitions</a></li>
                    <li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <section style="padding-top: 4%;">
    
        <div class="container-fluid top-container">
            <div class="row">
                <div class="col">
                    <div class="img-container"><img class="rounded" id="expandedImg" style="width:100%" src="assets/img/img1-min.jpg">
                        <div id="imgtext"></div>
                    </div>
                    <div class="row img-row" style="padding-right: 10px;padding-left: 10px;">
                        <div class="col column"><img class="img-thumbnail img-fluid" src="assets/img/img1-min.jpg" onclick="myFunction(this);" alt="image 1"></div>
                        <div class="col column"><img class="img-thumbnail img-fluid" src="assets/img/img2-min.jpg" onclick="myFunction(this);" alt="image 2"></div>
                        <div class="col column"><img class="img-thumbnail img-fluid" src="assets/img/img3-min.jpg" onclick="myFunction(this);" alt="image 3"></div>
                        <div class="col column"><img class="img-thumbnail img-fluid" src="assets/img/img4-min.jpg" onclick="myFunction(this);" alt="image 4"></div>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label class="form-label">Brand:</label> <br>
                        <label class="form-label">Model:</label> <br>
                        <label class="form-label">Price:</label> <br>
                        <label class="form-label">Warranty:</label> <br>  
                        <div>
                        <label class="form-label">Available colors:</label>
                        </div>
                    </div>  
                    
                </div>
                <div class="col">
                        <fieldset>
                            <legend><i class="fa fa-truck"></i> Buy Order</legend>
                        </fieldset>
                        <div class="has-feedback form-group mb-3"><label class="form-label" for="from_name">Full Name</label><input type="text" class="form-control" id="from_name" tabindex="-1" name="from_name" required></div>
                        <div class="has-feedback form-group mb-3"><label class="form-label" for="from_name">Mobile Number</label><input type="tel" class="form-control" id="from_name" tabindex="-1" name="from_name" required></div>
                        <div class="has-feedback form-group mb-3"><label class="form-label" for="from_email">Email</label><input type="email" class="form-control" id="from_email" name="from_email" required></div>
                        <div class="has-feedback form-group mb-3"><label class="form-label" for="from_email">ID Number</label><input type="text" class="form-control" id="from_email" name="from_email" required></div>
                        <label class="form-label" for="from_name">  Desired color</label>
                        <div id="target"><input type="color" class="form-control form-control-color" /></div>
                        <div class="row">
                                <div class="has-feedback form-group mb-3"><label class="form-label" for="from_phone">Address</label>
                                    <div class="col"><input type="text" class="form-control" id="from_phone" name="subject" placeholder="City" /></div>
                                    <div class="col"><input type="text" class="form-control" id="from_phone" name="subject" placeholder="Town" /></div>
                        </div>
                        <div class="form-group mb-3"><label class="form-label" for="comments">Additional Notes About Product </label><textarea class="form-control" id="comments" name="Comments" rows="2"></textarea></div>
                        <div class="form-group mb-3"><a href="thank-you.html"><button class="btn btn-primary active d-block w-100" style="background-color:#16c74b;" type="submit">Submit <i class="fa fa-chevron-circle-right"></i></button></a></div>
                </div>
            </div>
        </div>

    </section>
    <div id="footer" class="flex-wrap">
        <div id="image-box" class="col"><img id="footer-img" src="assets/img/unnamed.png"></div>
        <div id="end-box" class="col">
            <div id="end-content">
                <a href="/live.html"><h1 style="color: rgb(255,255,255);">Our works</h1></a>
                <ul class="list-unstyled">
                    <li style="color: rgb(255,255,255);font-size: 19px;">Phone:&nbsp;<a href="tel:+963932895825"><span style="color: rgb(69,73,78);">+963932895825</span></a><br></li>
                    <li style="color: rgb(255,255,255);font-size: 19px;">E-Mail:&nbsp;<a href="mailto:Syrjara@gmail.com"><span style="color: rgb(69,73,78);">syrjara@gmail.com</span></a><br></li>
                </ul> <a href="/contact-us.html"> <button class="btn btn-primary" id="form-btn" type="button"><i class="fa fa-envelope-o"></i>&nbsp;Contact-us</button></a>
                <div id="info-some-buttons" class="some" style="display: flex;justify-content: center;">
                    <ul class="some-list">
                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                        <li class="whatsapp"><a href="https://wa.link/"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="assets/js/vanilla-zoom.js"></script>
    <script src="assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="assets/js/theme.js"></script>
    <script src="assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="assets/js/Panel-Element-1.js"></script>
    <script src="assets/js/Panel-Element.js"></script>
    <script src="assets/js/Simple-Side-Nav.js"></script>
    <script src="assets/js/Simple-Slider.js"></script>
    <script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/0b51cec2d899412ea501d9269bffcda03dbf932c25e343a4b206a355923ba199.js"></script>

</body>

</html>