routes/web.php
<?php
		// $connection = new mysqli("localhost","root","","projectems");
		// $stet = $connection->prepare("select * from exhibtions");
		// $stet->execute();
		// $result = $stet->get_result();
		// while ($row = $result->fetch_assoc()) {
		// echo $row["Exhibition_Name"];
		// }
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function(){ 


Route::get('/', function () {
    return view('welcome');
});

Route::resource('Adminex','AdminexController');

Route::resource('Exhibtions','ExhibtionsController');

Route::resource('Buy','BuyController');

//Route::get('Merch', [ 'as' => 'Merch', 'uses' => 'MerchController@index']);

//Route::resource('Merch', 'MerchController');
Route::resource('Merch','MerchController' );
//Route::get('/home', 'MerchController@index')->name('home');



//Route::get('/home', 'HomeController@index')->name('home');


Route::resource('Admin','AdminController');

Route::resource('Category','CategoryController');

Route::get('finish', 'Lincontroller@finish');


Route::get('start', 'Lincontroller@start');

Route::resource('Contact','ContactController')->only(['create', 'store', 'index', 'thank']);

Route::resource('Product','ProductController');







	

	
});


Auth::routes();




Route::post('checklogin', 'SessionController@checklogin');
Route::get('login/success', 'SessionController@success');
Route::get('login/logout', 'SessionController@logout');
//Auth::routes();


Route::get('/home', function () {

	if(Auth::user()->isAdmin)
        return redirect()->route('Merch.index');
	else  return redirect()->route('Product.index');

});


Route::get('/wael', function () {
    if(Auth::user()->isAdmin)
        return redirect()->route('Product.index');

    return view('login');
});

app/Buy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buy extends Model
{
    protected $fillable = [ 'Full_Name', 'Mobile_Number', 'email', 'Number', 'City', 'Town', 'Comments'];
}

app/Http/Controllers/BuyController.php
<?php

namespace App\Http\Controllers;

use App\Buy;
use Illuminate\Http\Request;
USE DB;


class BuyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $products = DB::select("select * from products WHERE id = " . $request->id);
        
        return view('Buy.index' , ['products'=>$products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if($request->search){
        
        $search = $request->get('search');
        $buy = DB::table('buys')->where('Full_Name', 'like' , '%' . $search . '%')->paginate(5);
        return view('Buy.create',['buy'=>$buy]);
        }
        $buy = Buy::all();
        $buy = DB::select("select * from buys");
        return view('Buy.create' , ['buy'=>$buy]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $buy = new Buy;

        $buy->Full_Name = $request->Full_Name;
        $buy->Mobile_Number = $request->Mobile_Number;
        $buy->email = $request->email;
        $buy->Number = $request->Number;
        $buy->City = $request->City;
        $buy->Town = $request->Town;
        $buy->Comments = $request->Comments;

        $buy->save();

        return redirect()->route('Admin.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Buy  $buy
     * @return \Illuminate\Http\Response
     */
    public function show(Buy $buy)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Buy  $buy
     * @return \Illuminate\Http\Response
     */
    public function edit(Buy $buy)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Buy  $buy
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Buy $buy)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Buy  $buy
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Buy::findOrFail($id);

       $blog->delete();

       return redirect()->route('Buy.create');
    }
}

resources/views/Buy/create.blade.php
@extends('layou.index')

@section('content')
<header class="pc-header ">
        <div class="header-wrapper">    
            <div class="ml-auto">
                <ul class="list-unstyled">
                    <li class="dropdown pc-h-item">
                        <a class="pc-head-link dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <i class="material-icons-two-tone">search</i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right pc-h-dropdown drp-search">
                            <div class="px-3">
                            <form action="{{route('Buy.create')}}" method="get">
                                <div class="form-group mb-0 d-flex align-items-center">
                                    <i data-feather="search"></i>
                                    <input type="search" name="search" class="form-control border-0 shadow-none" placeholder="Search here. . .">
                                </div>
                            </form>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown pc-h-item">
                        <a class="pc-head-link dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            <span>
                                <span class="user-name">{{\Illuminate\Support\Facades\Auth::user()->name}}</span>
                                <span class="user-desc">@lang('The.Exhibitioin Admin')</span>

                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right pc-h-dropdown">
                            <div class=" dropdown-header">                          </div>

                            <a href="/login/logout" class="dropdown-item" >
                                <i class="material-icons-two-tone">chrome_reader_mode</i>
                                <span>@lang('The.Logout')</span>
                            </a>
                        </div>
                    </li>
                </ul>
                
            </div>

        </div>
    </header>
    <div class="pc-container">
        <div class="pcoded-content">
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <div class="page-header-title">
                                <h5 class="m-b-10">@lang('The.Dashboard')</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="exadmin.html">@lang('The.Home')</a></li>
                                <li class="breadcrumb-item">@lang('The.Manage My Exhibitioin')</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            
                            <th>@lang('The.Full Name')</th>
                            <th>@lang('The.Mobile Number')</th>
                            <th>@lang('The.email')</th>
                            <th>@lang('The.Number')</th>
                            <th>@lang('The.City')</th>
                            <th>@lang('The.Town')</th>
                            <th>@lang('The.Comments')</th>
                            <th>@lang('The.action')</th>

                        </thead>
                        <tbody>
                @foreach($buy as $by )
                    <tr>
                        <td>{{ $by->Full_Name }}</td>
                        <td>{{ $by->Mobile_Number }}</td>
                        <td>{{ $by->email }}</td>
                        <td>{{ $by->Number }}</td>
                        <td>{{ $by->City }}</td>
                        <td>{{ $by->Town }}</td>
                        <td>{{ $by->Comments }}</td>
                        <td>
                            <form method="POST" action="{{ route('Buy.destroy', [$by->id]) }}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit">@lang('The.Delete')</button>
                            </form>
                        </td>
                    </tr>     
            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
            
    <script src="/asset/js/vendor-all.min.js"></script>
    <script src="/asset/js/plugins/bootstrap.min.js"></script>
    <script src="/asset/js/plugins/feather.min.js"></script>
    <script src="/asset/js/pcoded.min.js"></script>

<script src="/asset/js/plugins/apexcharts.min.js"></script>

<script src="/asset/js/pages/dashboard-sale.js"></script>


@endsection

resources/views/Buy/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>The.Buy it  - EM-S-ITE</title>
    <link rel="stylesheet" href="/assets/css/Responsive-footer.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Horizontal.css">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/fonts/material-icons.min.css">
    <link rel="stylesheet" href="/assets/fonts/typicons.min.css">
    <link rel="stylesheet" href="/assets/css/--mp---Masonry-Gallery-with-Loader.css">
    <link rel="stylesheet" href="/assets/css/-Filterable-Gallery-with-Lightbox-BS4-.css">
    <link rel="stylesheet" href="/assets/css/Bootstrap-Image-Uploader.css">
    <link rel="stylesheet" href="/assets/css/Drag--Drop-Upload-Form.css">
    <link rel="stylesheet" href="/assets/css/Drag-Drop-File-Input-Upload.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar-1.css">
    <link rel="stylesheet" href="/assets/css/gradient-navbar.css">
    <link rel="stylesheet" href="/assets/css/Header-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/css/iziToast.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css">
    <link rel="stylesheet" href="/assets/css/Image_center.css">
    <link rel="stylesheet" href="/assets/css/Image-Tab-Gallery-Vertical.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="/assets/css/Map-Clean.css">
    <link rel="stylesheet" href="/assets/css/Masonry-gallery-cards-responsive.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-1.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-2.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element-3.css">
    <link rel="stylesheet" href="/assets/css/Panel-Element.css">
    <link rel="stylesheet" href="/assets/css/Projects-Clean.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">
    <link rel="stylesheet" href="/assets/css/Simple-Side-Nav.css">
    <link rel="stylesheet" href="/assets/css/Simple-Slider.css">
    <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css">
    <link rel="icon" href="/assets/img/logo.png" type="image/x-icon">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar" style="height: 11%;width: 100%;">
        <div class="container"><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><i class="fa fa-th-list"></i></button><img data-aos="fade" data-aos-delay="100" data-aos-once="true" src="/assets/img/logo.png" style="width: 90px;height: 70px;margin: -20px;padding: 0px;font-size: 17px;"><img src="/assets/img/EMSITE.png" style="height: 41px;width: 153px;margin: 1px 0px;padding: 0px 0px;">
            <div class="collapse navbar-collapse" id="navcol-1" style="height: 40px;width: 979.7px;">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="/start" style="width: 43px;">@lang('The.HOME')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Contact.create')}}">@lang('The.CONTACT-US')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/finish">@lang('The.OUR WORKS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Exhibtions.create')}}">@lang('The.LIVE EXHIBITIONS')</a></li>
                    <li class="nav-item"><a class="nav-link" href="/login">@lang('The.LOGIN')</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('Merch.create')}}">@lang('The.Merch')</a></li>
                </ul>
                <div class="dropdown"><button class="btn btn-primary dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button">Language </button>
    <div class="dropdown-menu">
    <ul>
        @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
           <li>
            <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
             {{ $properties['native'] }}
            </a>
            </li>
        @endforeach
    </ul>
    </ul>
            </div>
    </div>
            </div>
        </div>
    </nav>
    <section style="padding-top: 4%;">
    
        <div class="container-fluid top-container">
            <div class="row">
                <div class="col">
                    <div class="img-container">
                        <img class="rounded" id="expandedImg" style="width:100%" src="/assets/img/f29a1ebaf6ba41c8871ee1ace3098555.png">
                        <div id="imgtext"></div>
                    </div>
                    @foreach($products as $product)
                    <div class="row img-row" style="padding-right: 10px;padding-left: 10px;">
                        <div class="col column">
            <img class="img-thumbnail img-fluid" src="/ProductsImage/{{$product->Model}}1.jpg" onclick="myFunction(this);" alt="image 1">
                        </div>
                        <div class="col column">
                            <img class="img-thumbnail img-fluid" src="/ProductsImage/{{ $product->Model}}2.jpg" onclick="myFunction(this);" alt="image 2">
                        </div>
                        <div class="col column">
                            <img class="img-thumbnail img-fluid" src="/ProductsImage/{{ $product->Model}}3.jpg" onclick="myFunction(this);" alt="image 3">
                        </div>
                        <div class="col column">
                            <img class="img-thumbnail img-fluid" src="/ProductsImage/{{ $product->Model}}4.jpg" onclick="myFunction(this);" alt="image 4">
                        </div>
                    </div>
                    
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label class="form-label">@lang('The.Brand:')</label> <span>{{$product->Brand}}</span> <br>
                        <label class="form-label">@lang('The.Model:')</label> <span>{{$product->Model}}</span> <br>
                        <label class="form-label">@lang('The.Price:')</label> <span>{{$product->Price}}</span> <br>
                        <label class="form-label">@lang('The.Warranty:')</label> <span>{{$product->Warranty}}</span> <br>  
                        
                    </div>  
                    
                </div>
                 @endforeach
                <div class="col">
                <fieldset>
                <legend><i class="fa fa-truck"></i>@lang('The.Buy Order')</legend>
                </fieldset>
<form action="{{route('Buy.store')}}" method="post">
    @csrf
                <div class="has-feedback form-group mb-3">
                <label class="form-label" for="from_name">@lang('The.Full Name')</label>
                <input type="text" class="form-control" id="from_name" tabindex="-1" name="Full_Name" required>
                </div>
                <div class="has-feedback form-group mb-3">
                <label class="form-label" for="from_name">@lang('The.Mobile Number')</label>
                <input type="tel" class="form-control" id="from_name" tabindex="-1" name="Mobile_Number" required>
                </div>
                <div class="has-feedback form-group mb-3">
                    <label class="form-label" for="from_email">@lang('The.Email')</label>
                    <input type="email" class="form-control" id="from_email" name="email" required></div>
                <div class="has-feedback form-group mb-3">
                <label class="form-label" for="from_email">@lang('The.ID Number')</label><input type="text" class="form-control" id="from_email" name="Number" required>
             </div>

            <div class="row">
             <div class="has-feedback form-group mb-3"><label class="form-label" for="from_phone">@lang('The.Address')</label>
             <div class="col">
<input type="text" class="form-control" id="from_phone" name="City" placeholder="City" /></div>
             <div class="col">
<input type="text" class="form-control" id="from_phone" name="Town" placeholder="Town" /></div>
        </div>
     <div class="form-group mb-3">
<label class="form-label" for="comments">@lang('The.Additional Notes About Product') </label>
<textarea class="form-control" id="comments" name="Comments" rows="2"></textarea>
</div>
<div class="form-group mb-3"><a href="thank-you.html">
<button class="btn btn-primary active d-block w-100" style="background-color:#16c74b;" type="submit">@lang('The.Submit') 
<i class="fa fa-chevron-circle-right"></i>
</button></a>
</div>
    </form>
                </div>
            </div>
        </div>

    </section>
    <div id="footer" class="flex-wrap">
        <div id="image-box" class="col"><img id="footer-img" src="/assets/img/unnamed.png"></div>
        <div id="end-box" class="col">
            <div id="end-content">
                <a href="/live.html"><h1 style="color: rgb(255,255,255);">@lang('The.Our works')</h1></a>
                <ul class="list-unstyled">
                    <li style="color: rgb(255,255,255);font-size: 19px;">@lang('The.Phone:')&nbsp;<a href="tel:+963932895825"><span style="color: rgb(69,73,78);">+963932895825</span></a><br></li>
                    <li style="color: rgb(255,255,255);font-size: 19px;">@lang('The.E-Mail:')&nbsp;<a href="mailto:Syrjara@gmail.com"><span style="color: rgb(69,73,78);">syrjara@gmail.com</span></a><br></li>
                </ul> <a href="/contact-us.html"> <button class="btn btn-primary" id="form-btn" type="button"><i class="fa fa-envelope-o"></i>&nbsp;@lang('The.Contact-us')</button></a>
                <div id="info-some-buttons" class="some" style="display: flex;justify-content: center;">
                    <ul class="some-list">
                        <li class="facebook"><a href="https://www.facebook.com/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
                        <li class="instagram"><a href="https://www.instagram.com/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
                        <li class="whatsapp"><a href="https://wa.link/"><i class="fa fa-whatsapp fa-2x" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdn.rawgit.com/digistate/resouces/master/multipleFilterMasonry.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="https://cdn.rawgit.com/desandro/masonry/master/dist/masonry.pkgd.min.js"></script>
    <script src="/assets/js/vanilla-zoom.js"></script>
    <script src="/assets/js/--mp---Masonry-Gallery-with-Loader.js"></script>
    <script src="/assets/js/-Filterable-Gallery-with-Lightbox-BS4-.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/Bootstrap-Image-Uploader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
    <script src="/assets/js/Image-Tab-Gallery-Vertical.js"></script>
    <script src="/assets/js/Panel-Element-1.js"></script>
    <script src="/assets/js/Panel-Element.js"></script>
    <script src="/assets/js/Simple-Side-Nav.js"></script>
    <script src="/assets/js/Simple-Slider.js"></script>
    <script async type="text/javascript" src="https://userlike-cdn-widgets.s3-eu-west-1.amazonaws.com/0b51cec2d899412ea501d9269bffcda03dbf932c25e343a4b206a355923ba199.js"></script>

</body>

</html>